### ISSUE TITLE
Problem with install standalone version.

### ISSUE THREAD

**Issue by sumrakx** [OrienteerBAP/Orienteer#455]
Hi people, i have a problem with installer of "standalone" version. I downloaded the latest version of "orienteer.war" file, after that I installed jdk version, open console and wrote "jar -xvf orienteer.war". Now i have 2 folders and i don't have any idea what to do next. Mayby I need to run it with some other soft or compiler?

**Comment by PhantomYdn** [comment]
Hi! For standalone version please use `orienteer-standalone.jar`. It can be downloaded from this page: https://github.com/OrienteerBAP/Orienteer/releases/tag/v1.2 Start it as `java -jar orienteer-standalone.jar`. First run can take a while because database will be installed, modules applied and etc. After first run it's commonly starting within 10 sec.

orienteer.war is version to be deployed into some application server: tomcat, weblogic or something else.
Also we are recommending to use "docker" version of Orienteer: https://orienteer.gitbooks.io/orienteer/content/installation_via_docker.html
Standalone version make sense if you are trying to install it on RaspberryPI for example.

**Comment by PhantomYdn** [comment]
Closing the issue as old. Please reopen if you have any subsequent questions
