### ISSUE TITLE
Docker. Correct ORIENTDB_URL if ORIENTDB_EMBEDDED=false?

### ISSUE THREAD

**Issue by Vladimir-Va** [OrienteerBAP/Orienteer#823]
Hello, i new in OrientDB and Orienteer, and if i set ORIENTDB_EMBEDDED=true, docker container running correctly.
But if i set ORIENTDB_EMBEDDED=false and ORIENTDB_URL=remote:172.18.0.1:2480/testdb app is not runing?

**Comment by PhantomYdn** [comment]
@Vladimir-Va ,  it's highly recommended to use embedded mode for running Orienteer. Only by this mode Orienteer has some performance advantages and ability to deploy and use Orienteer specific functions into OrientDB.

But, if you have to have OrientDB as external DB - let me take a look. Could you please do `docker logs <your_container>` and share with me logs?

**Comment by Vladimir-Va** [comment]
Thank you, @PhantomYdn. I was afraid the project was dead.
Let me explain why I am trying to connect remotely:
1. I did not find how you can create several different projects connected to different databases of one/or another OrientDB.
2. Accordingly, the idea was to install a container with OrientDB and add containers with Orienteer for each database.
3. I did not understand what other ports besides 8080: 8080 to open in the Orienteer container. (For example, by analogy with DB 2424: 2424 and 2480: 2480).
4. Included OrientDB Studio in EMBEDDED mode accessing by port 2480 or another port?
Frankly speaking, I decided that my container docker pull orientdb:3.2.0-tp3 (didn't find what it is tp3), удалил его, буду устанавливать docker pull orientdb:latest.
Thank you for your work.

**Comment by PhantomYdn** [comment]
Hello, Orienteer is more than alive:)

1. Right now for different projects connected to different OrientDB instances different containers should be created. In other words: 1 Orienteer = 1 OrientDB
2. I got it, but with having OrientDB embedded into Orienteer you can get more benefits: performance, less management (you manage 1 container instead of 2), more functionality (Orienteer deploys additional functions and methods into OrientDB)
3. You can open any ports which you wish from Orienteer container. For example you can add `-p 2480:2480` to open this port for direct connectivity to your OrientDB instance. If you use `docker-compose.yml` - add `2480:2480` into `ports` section. For more info: https://docs.docker.com/compose/compose-file/compose-file-v2/#ports
4. Correct. Btw, you just mentioned another problem which is solved by using OrientDB as embedded. Unfortunately, OrientDB has different bugs in different versions of DB, so we in Orienteer pretty frequently fix those bugs from our side to prevent that in Orienteer.

**Comment by PhantomYdn** [comment]
Closing issue as outdated
